# Generated by Django 4.0.3 on 2022-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_image_category_image_location_image_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='my_image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
